info: |-
    Show a heatmap alongside a parallel coordinates plot. Each row in the heatmap is linked with a line in the line plot.

    "gene_symbol" is extracted from row names of the input data if a gene_symbol column is not present.
    "cluster" is a factor used to break the rows of the input data into groups.

    This visualization can receive URL parameters of the form:
        http://localhost:8000/data-longitudinal_heatmap.html?url_param1=value1&url_param2=value2&url_param3=value3
    Available URL parameters include:
        cluster=[1|0] show (or don't show) rows in clusters
        group=[1|0] break up (or don't break up) the columns of the data into subsets, determined by the prefix of each column
            (ex: boston_day_1, boston_day_2, nyc_day_1, nyc_day_2 would be broken up into two columns for each city)
        no_heatmap=[1] hide the heatmap
        no_pcp=[1] hide the parallel coordinates plot
        no_rownames=[1] hide the row names of the heatmap

original_url:

demo: |-
    data <- matrix(rnorm(200), ncol = 8,nrow = 25)
    rownames(data) <- paste0("GENE_", 1:25)
    colnames(data) <- paste0("sample_", 1:8)
    clickme(data, "longitudinal_heatmap")

data_names:
    required:
    optional:
        - "gene_symbol"
        - "cluster"

params:
    title: "Longitudinal Heatmap"
    row_names: "genes"
    y_axis_name: "log-ratio"

scripts:
    - http://html5shim.googlecode.com/svn/trunk/html5.js
    - http://code.jquery.com/jquery-1.7.1.min.js
    - http://documentcloud.github.com/underscore/underscore.js
    - http://documentcloud.github.com/backbone/backbone.js
    - http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js
    - http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js
    - http://mbostock.github.com/d3/d3.js
    - helper.js
    - models/longitudinal_model.js
    - views/dashboard_view.js
    - views/heatmap_view.js
    - views/pcp_view.js

styles:
    - https://fonts.googleapis.com/css?family=Lobster
    - leanback_style.css
    - longitudinal.css

require_packages:

require_server: yes
