info: |-
    "color"

    Based on ideas from:
    http://bl.ocks.org/mbostock/3680957
    http://bl.ocks.org/stepheneb/1182434

original_url:

demo: |-
    clickme_points(rnorm(500),rnorm(500), colorize = sample(letters[1:9], 500, replace = TRUE))
    clickme_points(rnorm(50),rnorm(50), colorize = sample(letters[1:3], 50, replace = TRUE), palette = c(a="green", c = "red", b = "blue"))

scripts:
    - d3.v3.js
    - d3_aux.js
    - jquery.min.js
    - bootstrap-tooltip.v2_3.js

styles:
    - bootstrap-tooltip.css
    - clickme.css

require_packages:

require_server: no

require_coffeescript: yes
