info: |-

original_url:

demo: |-
    clickme_lines(mat(nrow=5,ncol=5), colorize = c("a","a","b","b","a"))
    clickme_lines(mat(nrow=5,ncol=5), colorize = c("a","a","b","b","a"), interpolate = "basis")

scripts:
    - d3.v3.js
    - d3_aux.js
    - jquery.min.js
    - bootstrap-tooltip.v2_3.js

styles:
    - clickme.css
    - bootstrap-tooltip.css

require_packages:

require_server: no

require_coffeescript: yes
